### ISSUE TITLE
Update README to link to a paper

### ISSUE THREAD

**Issue by ciphergoth** [afDursun/Kyber-PAKE-C#1]
The README doesn't explain how Kyber is used to build a PAKE - is this OCAKE based? Please update the README to add info on what the proposed PAKE is :) thanks!

**Comment by afDursun** [comment]
Thanks for your suggestions :)

**Comment by ciphergoth** [comment]
Thanks for your response! I'm still so confused though - is this based on a paper already published, or is there a paper forthcoming on what you're building here?

**Comment by afDursun** [comment]
This article has yet to be published. It is under review now. We hope that it will be published in this year.  We uploaded the codes to explain how we obtained the implementation results of our paper.

**Comment by ciphergoth** [comment]
ah great - looking forward to reading it!

**Comment by afDursun** [comment]
Our article has been published. README.md file has been updated.
